name: Triggered workflow

on:
  workflow_run:
    workflows:
      - "Workflow 1"
      - "Workflow 2"
      - "Workflow 3"
    types:
      - completed

jobs:
  do_something:
    name: Successful job
    runs-on: ubuntu-latest

    steps:
      - run: echo "Only supposed to run if all three precedent workflows succeed"
